# Generated by Django 2.2 on 2019-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Select one', 'Select one'), ('Male', 'Male'), ('Female', 'Female')], default='Select one', max_length=2)),
                ('contact_phone', models.IntegerField(max_length=50)),
                ('description', models.TextField(max_length=254)),
            ],
        ),
    ]
