# Generated by Django 2.2 on 2019-05-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150, null=True)),
                ('ubicacion', models.CharField(max_length=150, null=True)),
                ('fnacimiento', models.DateField(null=True)),
                ('foto_path', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('genero', models.CharField(choices=[('s', 'Selecciona uno'), ('m', 'Masculino'), ('f', 'Femenino')], default='s', max_length=1)),
                ('tipo_deporte', models.CharField(choices=[('a', 'Ambos'), ('m', 'Masculino'), ('f', 'Femenino')], default='a', max_length=1)),
                ('telefono', models.IntegerField(null=True)),
                ('eactual', models.CharField(max_length=150, null=True)),
                ('altura', models.IntegerField(null=True)),
                ('peso', models.IntegerField(null=True)),
                ('interesadoen', models.TextField(max_length=500, null=True)),
                ('nacionalidad', models.CharField(max_length=200, null=True)),
                ('curriculum', models.CharField(max_length=150, null=True, unique=True)),
                ('cpresentacion', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Red_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('f', 'Facebook'), ('t', 'Twitter'), ('i', 'Instagram'), ('y', 'YouTube'), ('b', 'Blog')], max_length=2)),
                ('enlace', models.CharField(max_length=150)),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia_sports_agency.Usuario')),
            ],
        ),
    ]
