# Generated by Django 2.2 on 2019-05-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='red_social',
            old_name='usuario_fk',
            new_name='usuario',
        ),
    ]
