# Generated by Django 2.2 on 2019-04-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_phone',
            field=models.IntegerField(),
        ),
    ]
