# Generated by Django 2.2 on 2019-05-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extremidad_dominante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='extremidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sia_sports_agency.Extremidad_dominante'),
        ),
    ]
