# Generated by Django 2.2 on 2019-05-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0005_auto_20190520_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('path_icono', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('deporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sia_sports_agency.Deporte')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='paises',
            field=models.ManyToManyField(to='sia_sports_agency.Pais'),
        ),
    ]
