# Generated by Django 2.2 on 2019-06-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0008_auto_20190603_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrsena_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sia_sports_agency.Posicion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_path',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
