# Generated by Django 2.2 on 2019-06-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0009_auto_20190603_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrsena_1',
            new_name='contrasena_1',
        ),
    ]
