# Generated by Django 2.2 on 2019-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0010_auto_20190603_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='posicion',
        ),
        migrations.AddField(
            model_name='deporte',
            name='requiere_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posiciones',
            field=models.ManyToManyField(to='sia_sports_agency.Posicion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=1),
        ),
    ]
