# Generated by Django 2.2 on 2019-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0012_red_social_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='red_social',
            name='nombre',
            field=models.CharField(choices=[('f', 'Facebook'), ('t', 'Twitter'), ('i', 'Instagram'), ('y', 'YouTube'), ('b', 'Blog')], max_length=150),
        ),
    ]
