# Generated by Django 2.2 on 2019-06-26 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0013_auto_20190616_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
