# Generated by Django 2.2 on 2019-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0014_mensaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.IntegerField(default=0, max_length=500),
        ),
    ]
