# Generated by Django 2.2 on 2019-07-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0015_mensaje_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.IntegerField(default=0),
        ),
    ]
