# Generated by Django 2.2 on 2019-07-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0016_auto_20190710_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='n_visitas',
            field=models.IntegerField(default=0),
        ),
    ]
