# Generated by Django 2.2 on 2019-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0017_usuario_n_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ruta_cromo',
            field=models.CharField(default='C:\\Users\\usuario\\Projects\\sia_project\\sia_project\\sia_sports_agency\\static\\users\\videos-perfil\\silueta_defecto.png', max_length=150),
        ),
    ]
