# Generated by Django 2.2 on 2019-07-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0019_remove_usuario_ruta_cromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ruta_cromo',
            field=models.CharField(default='sia_sports_agency\\static\\users\\videos-perfil\\silueta_defecto.png', max_length=150),
        ),
    ]
