# Generated by Django 2.2 on 2019-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0021_remove_usuario_ruta_cromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ruta_cromo',
            field=models.CharField(default='users\\img-perfil\\silueta_defecto.png', max_length=150),
        ),
    ]
