# Generated by Django 2.2 on 2019-07-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0022_usuario_ruta_cromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img_perfil',
            field=models.CharField(default='users\\img-perfil\\silueta_defecto.png', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_acceso',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ruta_cromo',
            field=models.CharField(max_length=150),
        ),
    ]
