# Generated by Django 2.2 on 2019-08-10 08:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0025_auto_20190720_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_altura',
            field=models.CharField(choices=[('cm', 'cm'), ('pulgadas', 'pulgadas')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_peso',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
    ]
