# Generated by Django 2.2 on 2019-08-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0026_auto_20190810_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena_2',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img_perfil',
            field=models.CharField(default='sia_sports_agency\\static\\users\\img-perfil\\silueta_defecto.png', max_length=150),
        ),
    ]
