# Generated by Django 2.2 on 2019-09-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_sports_agency', '0027_auto_20190819_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
